# Generated by Django 4.2.4 on 2023-08-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teacher_detail_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interested_categories',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
