# Generated by Django 4.2.4 on 2023-08-26 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studentcourseenrollemnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseenrollemnt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='main.student'),
        ),
    ]
